# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1074, 812)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.input_ = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_.sizePolicy().hasHeightForWidth())
        self.input_.setSizePolicy(sizePolicy)
        self.input_.setObjectName("input_")
        self.verticalLayout_3.addWidget(self.input_)
        self.load_pretext = QtWidgets.QPushButton(self.centralwidget)
        self.load_pretext.setObjectName("load_pretext")
        self.verticalLayout_3.addWidget(self.load_pretext)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.manual = QtWidgets.QCheckBox(self.centralwidget)
        self.manual.setObjectName("manual")
        self.horizontalLayout_7.addWidget(self.manual)
        self.auto_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.auto_2.setObjectName("auto_2")
        self.horizontalLayout_7.addWidget(self.auto_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.meta = QtWidgets.QCheckBox(self.centralwidget)
        self.meta.setObjectName("meta")
        self.horizontalLayout.addWidget(self.meta)
        self.metaplusimage = QtWidgets.QCheckBox(self.centralwidget)
        self.metaplusimage.setObjectName("metaplusimage")
        self.horizontalLayout.addWidget(self.metaplusimage)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.l_dicom = QtWidgets.QPushButton(self.centralwidget)
        self.l_dicom.setObjectName("l_dicom")
        self.verticalLayout.addWidget(self.l_dicom)
        self.l_image = QtWidgets.QPushButton(self.centralwidget)
        self.l_image.setObjectName("l_image")
        self.verticalLayout.addWidget(self.l_image)
        self.l_folder = QtWidgets.QPushButton(self.centralwidget)
        self.l_folder.setObjectName("l_folder")
        self.verticalLayout.addWidget(self.l_folder)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_4.addWidget(self.listWidget)
        self.add = QtWidgets.QPushButton(self.centralwidget)
        self.add.setObjectName("add")
        self.verticalLayout_4.addWidget(self.add)
        self.switch_2 = QtWidgets.QPushButton(self.centralwidget)
        self.switch_2.setObjectName("switch_2")
        self.verticalLayout_4.addWidget(self.switch_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.listWidget_2 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_2.setObjectName("listWidget_2")
        self.verticalLayout_5.addWidget(self.listWidget_2)
        self.remove = QtWidgets.QPushButton(self.centralwidget)
        self.remove.setObjectName("remove")
        self.verticalLayout_5.addWidget(self.remove)
        self.pretext1 = QtWidgets.QPushButton(self.centralwidget)
        self.pretext1.setObjectName("pretext1")
        self.verticalLayout_5.addWidget(self.pretext1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.output = QtWidgets.QPushButton(self.centralwidget)
        self.output.setObjectName("output")
        self.verticalLayout_6.addWidget(self.output)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.metadata = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.metadata.sizePolicy().hasHeightForWidth())
        self.metadata.setSizePolicy(sizePolicy)
        self.metadata.setObjectName("metadata")
        self.verticalLayout_6.addWidget(self.metadata)
        self.anonymise = QtWidgets.QPushButton(self.centralwidget)
        self.anonymise.setObjectName("anonymise")
        self.verticalLayout_6.addWidget(self.anonymise)
        self.t2 = QtWidgets.QPushButton(self.centralwidget)
        self.t2.setObjectName("t2")
        self.verticalLayout_6.addWidget(self.t2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1074, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "DICOM Anonymiser :)"))
        self.load_pretext.setText(_translate("mainWindow", "Load Pretext"))
        self.manual.setText(_translate("mainWindow", "Manual"))
        self.auto_2.setText(_translate("mainWindow", "Auto"))
        self.meta.setText(_translate("mainWindow", "Metadata"))
        self.metaplusimage.setText(_translate("mainWindow", "Metadata + Image"))
        self.l_dicom.setText(_translate("mainWindow", "DICOM"))
        self.l_image.setText(_translate("mainWindow", "IMAGE"))
        self.l_folder.setText(_translate("mainWindow", "FOLDER"))
        self.label.setText(_translate("mainWindow", "Original"))
        self.label_2.setText(_translate("mainWindow", "Masked"))
        self.add.setText(_translate("mainWindow", "ADD"))
        self.switch_2.setText(_translate("mainWindow", "SWITCH"))
        self.remove.setText(_translate("mainWindow", "REMOVE"))
        self.pretext1.setText(_translate("mainWindow", "SAVE PRETEXT"))
        self.output.setText(_translate("mainWindow", "Output Destination"))
        self.label_3.setText(_translate("mainWindow", "Labels Identified"))
        self.anonymise.setText(_translate("mainWindow", "Anonymise"))
        self.t2.setText(_translate("mainWindow", "Full Mask"))
        self.menuFile.setTitle(_translate("mainWindow", "File"))
        self.menuHelp.setTitle(_translate("mainWindow", "Help"))
        self.menuAbout.setTitle(_translate("mainWindow", "About"))

